name: DooBee
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  provider: ^6.1.1
  easy_date_timeline: ^1.0.3
  flutter_slidable: ^3.0.1
  firebase_core: ^2.26.0
  cloud_firestore: ^4.15.7
  firebase_auth: ^4.17.7
  firebase_crashlytics: ^3.4.17
  text_divider: ^1.0.0
  icons_plus: ^5.0.0
  google_sign_in: '^6.2.1'
  animated_custom_dropdown: ^3.0.0
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  flutter_screenutil: ^5.9.1
  gradient_borders: ^1.0.0
  simple_gradient_text: ^1.3.0
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/images/@2x/
    - assets/images/@3x/
    - assets/images/dark_theme/

